spring.application.name=LifeSyncBackend

################################################
# PostgreSQL
################################################

spring.datasource.url=jdbc:postgresql://localhost:5432/lifesync
spring.datasource.username=postgres
spring.datasource.password=leang30122006
spring.datasource.driver-class-name=org.postgresql.Driver

################################################
# Hibernate
################################################

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

################################################
# Flyway
################################################

spring.flyway.enabled=false

################################################
# Server
################################################

server.port=8085
server.tomcat.basedir=./tomcat-temp
app.profile-images.directory=./uploads/profile-images

################################################
# JWT
################################################

jwt.secret=YourSuperSecretKeyMustBeAtLeast256BitsLongForHS256Algorithm123456789
jwt.expiration=86400000

################################################
# Mail
################################################

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=genzbuilder.otp@gmail.com
spring.mail.password=bwyy ejii umvb zvnz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

################################################
# Telegram Bot
################################################
telegram.bot.token=8734969889:AAHi3fiS79HWwcF7VQ9RBptTI6y-Tc3VJxg
telegram.bot.api-url=https://api.telegram.org/bot${telegram.bot.token}
