spring.application.name=LifeSyncBackend

spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

################################################
# PostgreSQL
################################################

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lifesync}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:leang30122006}
spring.datasource.driver-class-name=org.postgresql.Driver

################################################
# Hibernate
################################################

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

################################################
# Flyway
################################################

spring.flyway.enabled=false
spring.jackson.serialization.write-dates-as-timestamps=false

################################################
# Server
################################################

server.port=${SERVER_PORT:8085}
server.tomcat.basedir=./tomcat-temp
app.profile-images.directory=${UPLOAD_DIR:./uploads/profile-images}

################################################
# JWT
################################################

jwt.secret=${JWT_SECRET:YourSuperSecretKeyMustBeAtLeast256BitsLongForHS256Algorithm123456789}
jwt.expiration=${JWT_EXPIRATION_MS:86400000}

################################################
# Mail
################################################

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${GMAIL_USERNAME:}
spring.mail.password=${GMAIL_APP_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

################################################
# Telegram Bot
################################################
telegram.bot.token=${LIFESYNC_TELEGRAM_BOT_TOKEN:}
telegram.bot.api-url=${TELEGRAM_API_URL:https://api.telegram.org/bot}${telegram.bot.token}

################################################
# Gemini AI Assistant
################################################
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=${GEMINI_API_BASE_URL:https://generativelanguage.googleapis.com/v1beta}
gemini.model=${GEMINI_MODEL:gemini-3.6-flash}

################################################
# Logging File
################################################

logging.file.name=${LOGGING_FILE_NAME:logs/app.log}

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB

logging.level.root=${LOG_LEVEL_ROOT:INFO}
logging.level.com.lifesync_project.LifeSyncBackend=${LOG_LEVEL_APP:DEBUG}

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{requestId}] --- [%t] %-40.40logger{39} : %m%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{requestId}] --- [%t] %-40.40logger{39} : %m%n

################################################
# Cache Redis
################################################

spring.cache.type=redis

# Connection settings (adjust if using remote Redis or Docker)
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}


