spring.application.name=LifeSyncBackend

################################################
# PostgreSQL
################################################

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lifesync}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:leang30122006}
spring.datasource.driver-class-name=org.postgresql.Driver

################################################
# Hibernate
################################################

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

################################################
# Flyway
################################################

spring.flyway.enabled=false
spring.jackson.serialization.write-dates-as-timestamps=false

################################################
# Server
################################################

server.port=8085
server.tomcat.basedir=./tomcat-temp
app.profile-images.directory=./uploads/profile-images

################################################
# JWT
################################################

jwt.secret=${JWT_SECRET:YourSuperSecretKeyMustBeAtLeast256BitsLongForHS256Algorithm123456789}
jwt.expiration=86400000

################################################
# Mail
################################################

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME:genzbuilder.otp@gmail.com}
spring.mail.password=${GMAIL_APP_PASSWORD:bwyy ejii umvb zvnz}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

################################################
# Telegram Bot
################################################
telegram.bot.token=${LIFESYNC_TELEGRAM_BOT_TOKEN:}
telegram.bot.api-url=https://api.telegram.org/bot${telegram.bot.token}



################################################
# Logging File
################################################

logging.file.name=logs/app.log

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB

logging.level.root=INFO
logging.level.com.lifesync_project.LifeSyncBackend=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{requestId}] --- [%t] %-40.40logger{39} : %m%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{requestId}] --- [%t] %-40.40logger{39} : %m%n

################################################
# Cache Redis
################################################

spring.cache.type=redis

# Connection settings (adjust if using remote Redis or Docker)
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=your_password_if_any

