
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY app.jar /app/app.jar
ENV HOME=/tmp
EXPOSE 8085
USER 1001
ENTRYPOINT ["java", "-jar", "/app/app.jar", "--spring.profiles.active=openshift", "--spring.jpa.hibernate.ddl-auto=validate", "--spring.flyway.enabled=false", "--spring.liquibase.enabled=false", "--spring.sql.init.mode=never"]
