spring.datasource.url=jdbc:postgresql://localhost:5432/lifesync
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
spring.flyway.enabled=false
