ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_failures integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_email_attempts integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_send_attempts integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_window_started_at timestamp;
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_blocked_until timestamp;
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_last_sent_at timestamp;
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_purpose varchar(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram_chat_id varchar(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pending_telegram_chat_id varchar(255);
